# Checkov Configuration File
# Cấu hình cho việc kiểm tra bảo mật Terraform

# Thư mục cần scan
directory:
  - terraform

# Framework cần check
framework:
  - terraform
  - secrets

# Output format
output:
  - cli
  - json
  - junitxml

# Compact output (less verbose)
compact: false

# Quiet mode (only show failed checks)
quiet: false

# Download external Terraform modules
download-external-modules: true

# Evaluate variables
evaluate-variables: true

# Skip specific checks (nếu cần)
# Uncomment các checks bạn muốn skip
skip-check:
  # Skip checks that may not be applicable for dev/test environments
  # - CKV_AWS_79  # Ensure Instance Metadata Service Version 1 is not enabled
  # - CKV_AWS_135 # Ensure that EC2 is EBS optimized
  # - CKV_AWS_126 # Ensure that detailed monitoring is enabled for EC2 instances

# External checks directory (if you have custom checks)
# external-checks-dir: .checkov-policies

# Baseline file to compare against (useful for PR reviews)
# baseline: .checkov.baseline

# Suppression of specific resource checks
# Use inline comments in Terraform files:
# Example: #checkov:skip=CKV_AWS_79:Reason for skipping

